/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class PSSpecifier;

@interface PSEditingPane : UIView
{
    PSSpecifier *_specifier;	// 32 = 0x20
    id _delegate;	// 36 = 0x24
    unsigned int _requiresKeyboard:1;	// 40 = 0x28
}

+ (CGSize)defaultSize;	// IMP=0x3176e200
+ (id)defaultBackgroundColor;	// IMP=0x3176e48c
- (id)initWithFrame:(CGRect)fp8;	// IMP=0x3176e164
- (BOOL)drawLabel;	// IMP=0x3176e2a0
@property(readonly) CGRect contentRect;
- (void)dealloc;	// IMP=0x3176e37c
- (void)setDelegate:(id)fp8;	// IMP=0x3176e3dc
@property(retain) PSSpecifier* preferenceSpecifier;
@property(retain) NSObject* preferenceValue;
- (BOOL)requiresKeyboard;	// IMP=0x3176e474
- (void)drawPinstripesInRect:(CGRect)fp8;	// IMP=0x3176e4d4
@property(readonly) NSString* specifierLabel;	// IMP=0x3176e52c
- (void)drawLabelInRect:(CGRect)fp8;	// IMP=0x3176e558
- (void)drawRect:(CGRect)fp8;	// IMP=0x3176e6d8
- (BOOL)wantsNewButton;	// IMP=0x3176e750
- (void)addNewValue;	// IMP=0x3176e758
- (void)editMode;	// IMP=0x3176e75c
- (void)doneEditing;	// IMP=0x3176e760
- (BOOL)handlesDoneButton;	// IMP=0x3176e764
- (BOOL)changed;	// IMP=0x3176e76c

@end

