#!/bin/bash

if [[ $1 == remove || $1 == upgrade || $1 == "abort-install" ]]; then
	iKeyEx-KBMan purge-layout 5RowQWERTY
	if [[ $1 != upgrade ]]; then
		iKeyEx-KBMan unregister-layout 5RowQWERTY
	fi
	exit 0
fi
