#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [[ $1 == install || $1 == upgrade ]]; then
	/usr/libexec/cydia/move.sh /Library/iKeyEx
	echo "";
	echo "";
	echo "";
	echo "If the iPhone/iPod Touch crashes, please go to Settings->iKeyEx->Troubleshooting and click [Email Diagnosis Info] to let me know.";
	echo "";
	echo "";
	echo "";
	if [[ ${CYDIA+@} ]]; then
	        eval "echo 'finish:restart' >&${cydia[0]}"
    	fi
fi
