#!/bin/bash

if [[ $1 == install ]]; then
	if [[ -e /var/mobile/Library/Keyboard/iKeyEx/templates-hClipboard.plist ]]; then
		mv /var/mobile/Library/Keyboard/iKeyEx/templates-hClipboard.plist /var/mobile/Library/Keyboard/iKeyEx\:hClipboard-templates.plist
	fi
	iKeyEx-KBMan add hClipboard
	exit 0
fi