/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSArray, UIImage, UIAccentedKeyCapStringView;

@interface UIAccentedCharacterView : UIView
{
    NSArray *m_characters;
    NSArray *m_caps;
    unsigned m_count;
    int m_expansion;
    int m_orientation;
    float m_stringWidth;
    UIImage *m_tubeImage;
    struct CGRect m_tubeRect;
    UIImage *m_grabberImage;
    struct CGRect m_grabberRect;
    UIAccentedKeyCapStringView *m_popupView;
    UIAccentedKeyCapStringView *m_selectedView;
    unsigned int m_selectedIndex;
    BOOL m_dragged;
    struct CGPoint m_dragPoint;
}

- (id)initWithFrame:(struct CGRect)frame variants:(NSArray*)accentslist expansion:(int)fp28 orientation:(int)orient;
- (void)dealloc;
- (void)setSelectedIndex:(int)fp8;
- (void)sendSelectedString;
- (unsigned int)moveCharactersAndCapsToAltSide:(unsigned int)fp8 position:(unsigned int)fp12 expansion:(int)fp16;
- (BOOL)canHandleHandEvent:(struct __GSEvent *)fp8;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)drawRect:(struct CGRect)fp8;

@end

