#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [[ $1 == remove ]]; then
	iKeyEx-KBMan removeall
	iKeyEx-KBMan purgeall
	rm -f /var/mobile/Library/Keyboard/iKeyEx/cache/*
	if [[ ${CYDIA+@} ]]; then
	        eval "echo 'finish:restart' >&${cydia[0]}"
    	fi
	exit 0
fi
