/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class CandWordString;

@interface CandWord : NSObject <NSCopying>
{
    CandWordString* _word;
}

- (CandWord*)initWithWord:(NSString*)word;
- (void)dealloc;
- (id)word;
- (const char *)wordUTF8String;
- (id)insertion;
- (unsigned int)deleteCount;
- (CandWord*)copyWithZone:(NSZone*)zone;
- (BOOL)isEqual:(CandWord*)candword;
- (unsigned int)hash;

@end

