/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>
#import <UIKit/UITextInputTraits.h>
#import <UIKit2/UIKeyboardLayoutProtocol.h>

@class UIKeyboardLanguageIndicator, NSString;

@interface UIKeyboardLayout : UIView <UIKeyboardLayoutProtocol> {}

- (id)initWithFrame:(CGRect)frm;
- (void)showKeyboardType:(UIKeyboardType)type withAppearance:(UIKeyboardAppearance)appr;

// keys are no longer active -- remove any active images (e.g. popup views, touch down images, etc.)
- (void)deactivateActiveKeys;

- (void)updateReturnKey;

// Update localized keys. Called from -[UIKeyboardImpl setInputMode:].
- (void)updateLocalizedKeys;

// Asks if auto shift is in effect (?). Called from -[UIKeyboardImpl updateShift].
- (BOOL)usesAutoShift;

// Set shift state. Called from -[UIKeyboardImpl setShift:].
- (void)setShift:(BOOL)shift;

// Asks if the shift key is held. Called from -[UIKeyboardImpl updateShift].
- (BOOL)isShiftKeyBeingHeld;
- (BOOL)isShiftKeyPlaneChooser;
- (BOOL)shiftKeyRequiresImmediateUpdate;
- (void)longPressAction;
- (BOOL)canHandleHandEvent:(struct __GSEvent *)fp8;
- (BOOL)handleHandEvent:(struct __GSEvent *)fp8;

// Event handler when the input is indeed cleared. Called from -[UIKeyboardImpl clearInput].
- (void)didClearInput;

// Return the candidate list (shouldn't this the job of UIKeyboardInputManager?)
// Just don't override this...
- (NSArray*)candidateList;

// Assign a label for a key.
// e.g. with candidate list enabled, an input manager may call
//  [theLayout setLabel:@"UI-NextCandidate" forKey:@"_keyid_space_"];
// note that you have to localize the string yourself.
- (void)setLabel:(NSString*)label forKey:(NSString*)keyid;

// This pair set the target & action for a key.
// e.g. with candidate list enabled, an input manager may call
//  [theLayout setTarget:theCandidateList forKey:@"_keyid_space_"];
//  [theLayout setAction:@selector(showNextCandidate) forKey:@"_keyid_space_"];
- (void)setTarget:(id)target forKey:(NSString*)keyid;
- (void)setAction:(SEL)action forKey:(NSString*)keyid;

- (void)setLongPressAction:(SEL)fp8 forKey:(id)fp12;

// Restore defaults for key. Called from -[UIKeyboardInputManager configureKeyboard:forCandidates:].
- (void)restoreDefaultsForKey:(NSString*)fp8;

// Restore defaults for all keys. Called from -[UIKeyboardImpl clearInput].
- (void)restoreDefaultsForAllKeys;

// Return the input mode indicator. Called from -[UIKeyboardImpl showInputModeIndicator].
- (UIKeyboardLanguageIndicator*)activationIndicatorView;

- (BOOL)shouldShowIndicator;
//- (void)handleHardwareKeyDownFromSimulator:(struct __GSEvent *)fp8;

@end