/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
#import <Preferences/Constants.h>

@class NSArray, NSDictionary, NSMutableDictionary, NSString;

@interface PSSpecifier : NSObject
{
    id target;	// 4 = 0x4
    SEL getter;	// 8 = 0x8
    SEL setter;	// 12 = 0xc
    SEL action;	// 16 = 0x10
    Class detailControllerClass;	// 20 = 0x14
	@package
    PSSpecifierType cellType;	// 24 = 0x18
	@protected
    Class editPaneClass;	// 28 = 0x1c
    int keyboardType;	// 32 = 0x20
    int autoCapsType;	// 36 = 0x24
    int autoCorrectionType;	// 40 = 0x28
    int textFieldType;	// 44 = 0x2c
    NSString *_name;	// 48 = 0x30
    NSArray *_values;	// 52 = 0x34
    NSDictionary *_titleDict;	// 56 = 0x38
    NSDictionary *_shortTitleDict;	// 60 = 0x3c
    id _userInfo;	// 64 = 0x40
    NSMutableDictionary *_properties;	// 68 = 0x44
}

+ (id)preferenceSpecifierNamed:(NSString*)fp8 target:(id)fp12 set:(SEL)fp16 get:(SEL)fp20 detail:(Class)fp24 cell:(PSSpecifierType)fp28 edit:(Class)fp32;	// IMP=0x317661e0
+ (id)groupSpecifierWithName:(NSString*)fp8;	// IMP=0x317662c4
+ (id)emptyGroupSpecifier;	// IMP=0x3176630c

+ (int)autoCapsTypeForString:(id)fp8;	// IMP=0x3176699c
+ (int)keyboardTypeForString:(id)fp8;	// IMP=0x31766a28
- (id)init;	// IMP=0x31766160
- (id)propertyForKey:(id)fp8;	// IMP=0x3176632c
- (void)setProperty:(id)fp8 forKey:(NSString*)fp12;	// IMP=0x31766358
- (void)removePropertyForKey:(NSString*)fp8;	// IMP=0x3176638c
- (void)setProperties:(id)fp8;	// IMP=0x317663b8
- (id)properties;	// IMP=0x3176640c
- (void)loadValuesAndTitlesFromDataSource;	// IMP=0x31766420
- (void)setValues:(id)fp8 titles:(id)fp12;	// IMP=0x31766528
- (void)setValues:(id)fp8 titles:(id)fp12 shortTitles:(id)fp16;	// IMP=0x31766554
- (void)setupIconImageWithPath:(id)fp8;	// IMP=0x3176670c
- (void)dealloc;	// IMP=0x317667d4
- (NSString*)description;	// IMP=0x317668b0

@property(readonly) NSString* identifier;
@property(copy) NSString* name;
@property(retain) NSDictionary* titleDictionary;
@property(retain) NSDictionary* shortTitleDictionary;
@property(retain) id values;
@property(assign) id userInfo;

- (void)setTarget:(id)fp8;	// IMP=0x31766d90
- (void)setKeyboardType:(int)fp8 autoCaps:(int)fp12 autoCorrection:(int)fp16;	// IMP=0x31766da4
- (int)titleCompare:(id)fp8;	// IMP=0x31766df0

@end

