#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [[ $1 == remove ]]; then
	rm /usr/lib/libiKeyEx.dylib
	rm /Library/MobileSubstrate/DynamicLibraries/PrefHooker-iKeyEx.dylib
	rm /Library/MobileSubstrate/DynamicLibraries/SBHooker-iKeyEx.dylib
	iKeyEx-KBMan removeall
	rm /var/mobile/Library/Keyboard/iKeyEx/cache/*
	if [[ ${CYDIA+@} ]]; then
	        eval "echo 'finish:restart' >&${cydia[0]}"
    	fi
fi