#!/bin/bash

iKeyEx-KBMan register "iKeyEx:5RowQWERTY" "5-Row QWERTY" 5RowQWERTY "=en_US"
if [[ $1 == install ]]; then
	iKeyEx-KBMan activate "iKeyEx:5RowQWERTY";
elif [[ $1 == upgrade ]]; then
	# Preserve the config.
	cd /Library/iKeyEx/Keyboards/5RowQWERTY.keyboard/;
	cp layout.plist ~layout.plist;
	cp Info.plist ~Info.plist;
fi;
exit 0;
