#!/bin/bash

if [[ $1 == install ]]; then
	iKeyEx-KBMan add 5RowQWERTY
	exit 0
elif [[ $1 == upgrade ]]; then
	# Preserve the config.
	cd /Library/iKeyEx/Keyboards/5RowQWERTY.keyboard/;
	cp layout.plist ~layout.plist;
	cp Info.plist ~Info.plist;
	exit 0;
fi
