#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [[ $1 == install ]]; then
	cd /var/mobile/Library/iKeyEx/lib/
	ln -s libiKeyEx.dylib /usr/lib/libiKeyEx.dylib
	ln -s PrefHooker-iKeyEx.dylib /Library/MobileSubstrate/DynamicLibraries/PrefHooker-iKeyEx.dylib
	ln -s SBHooker-iKeyEx.dylib /Library/MobileSubstrate/DynamicLibraries/SBHooker-iKeyEx.dylib

	if [[ ${CYDIA+@} ]]; then
	        eval "echo 'finish:restart' >&${cydia[0]}"
    	fi
elif [[ $1 == upgrade ]]; then
	if [[ ${CYDIA+@} ]]; then
	        eval "echo 'finish:restart' >&${cydia[0]}"
    	fi
fi