/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@class UIImage, UIView, NSString;
#import <CoreGraphics/CGGeometry.h>

typedef enum UIKeyType {
	UIKeyTypeNormal = 1,
	UIKeyTypeDelete = 3,
	UIKeyTypeSpace  = 4,
	UIKeyTypeReturn = 5,
	UIKeyTypeShift  = 6,
	UIKeyTypeInternational = 7
} UIKeyType;

typedef enum UIKeyDefinitionDownActionFlag {
	UIKeyFlagActivateKey           = 1,
	UIKeyFlagSendActionOnTouchDown = 2,
	UIKeyFlagPlaySound             = 4,
	UIKeyFlagShiftKey              = 0x10,
	UIKeyFlagInternationalKey      = 0x20,
	UIKeyFlagDeleteKey             = 0x40,
	UIKeyFlagHasLongPressAction    = 0x80,
	UIKeyFlagRomanAccents          = 0x8000,
	UIKeyFlagURLDomainVariants     = 0x10000,
	UIKeyFlagEmailDomainVariants   = 0x20000,
	UIKeyFlagCurrencyVariants      = 0x40000,	// ?
	UIKeyFlagFunctionKeysUnknown   = 0x80000
} UIKeyDefinitionDownActionFlag;

typedef enum UIKeyDefinitionUpActionFlag {
	UIKeyFlagOutputValue           = 2,		// do not set this field if the value is intended to be invisible, e.g. "shift", "delete", etc.
	UIKeyFlagDeactivateKey         = 8,
	UIKeyFlagSwitchPlane           = 0x100,
	UIKeyFlagToggleShift           = 0x400,
	UIKeyFlagStopAutoDelete        = 0x800,
	UIKeyFlagChangeInputMode       = 0x1000,	// effective only for the intl key.
	UIKeyFlagSkipCandidateList     = 0x10000
} UIKeyDefinitionUpActionFlag;

typedef struct {
    unsigned char pathIndex;
    unsigned char pathIdentity;
    unsigned char pathProximity;
    float pathPressure;
    float pathMajorRadius;
    struct CGPoint pathLocation;
    struct __GSWindow *pathWindow;
} PathInfo;

typedef struct UIKeyDefinition {
	CGRect bg_area;		// +0,  the area of the key in the background image.
	CGRect pop_bg_area;	// +16,	the area of the pop up view background in the image map. (The origin may be shifted a bit to the left or right)
	CGRect pop_char_area;// +32,	the area of the pop up view character in the image map.
	CGRect accent_frame;	// +48,	the frame of the UIAccentedCharactersView.
	CGRect pop_padding;	// +64, the origin of the pop up view, and the padding of the character.
	NSString* value;			// +80, value to send when not shifted.
	NSString* shifted;			// +84, value to send when shifted.
	enum UIKeyDefinitionDownActionFlag down_flags;	// +88, 
	enum UIKeyDefinitionUpActionFlag up_flags;		// +92, 
	enum UIKeyType key_type;	// +96
	NSString* pop_type;			// +100
} UIKeyDefinition;				// sizeof = 104

typedef struct {
    CGRect left;
    CGRect middle;
    CGRect right;
} CDAnonymousStruct8;