/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class NSMutableArray, NSTimer, UIImageView, UILabel, UIPushButton, UIView;

@interface UICalloutView : UIControl
{
    UIImageView *_leftCap;
    UIImageView *_rightCap;
    UIImageView *_topAnchor;
    UIImageView *_bottomAnchor;
    UIImageView *_leftBackground;
    UIImageView *_rightBackground;
    UIPushButton *_button;
    UILabel *_title;
    UILabel *_subtitle;
    UILabel *_temporary;
    UIView *_leftView;
    struct {
        struct CGPoint origin;
        struct CGPoint offset;
        int position;
        struct CGPoint desiredPoint;
        struct CGRect desiredBounds;
    } _anchor;
    struct CGRect _frame;
    id _delegate;
    struct {
        unsigned int animated:1;
        unsigned int didMoveCalled:1;
        unsigned int hasPendingAnimatedLayout:1;
        unsigned int reserved:29;
    } _flags;
    NSMutableArray *_fadeInViews;
    NSMutableArray *_fadeOutViews;
    NSTimer *_layoutAnimationTimer;
}

+ (id)_buttonImage;
+ (id)_buttonImagePressed;
+ (id)_backgroundImage;
+ (id)_leftCapImage;
+ (id)_rightCapImage;
+ (id)_topAnchorImage;
+ (id)_bottomAnchorImage;
+ (float)defaultHeight;
+ (id)sharedCalloutView;
- (void)_setLeftView:(id)fp8;
- (void)_scheduleViewToFadeIn:(id)fp8;
- (void)_scheduleViewToFadeOut:(id)fp8;
- (void)setLeftView:(id)fp8 animated:(BOOL)fp12;
- (void)setSubtitle:(id)fp8 animated:(BOOL)fp12;
- (void)_setLayoutAnimationTimer:(id)fp8;
- (void)_layoutAnimation;
- (void)_scheduleLayoutAnimation;
@property(retain) UIView* leftView;
- (void)_fadeViewsIn:(BOOL)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
@property(retain) NSString* title;
@property(retain) NSString* subtitle;
@property(retain) NSString* temporaryTitle;
@property(assign) UILineBreakMode titleLineBreakMode;
@property(assign) UILineBreakMode subtitleLineBreakMode;
@property(assign) CGPoint offset;
- (struct CGPoint)anchorPoint;
- (void)getActualAnchorPoint:(struct CGPoint *)fp8 frame:(struct CGRect *)fp12 position:(int *)fp16 forDesiredAnchorPoint:(struct CGPoint)fp20 boundaryRect:(struct CGRect)fp28;
- (void)_setOriginForScale:(float)fp8;
- (void)_layoutSubviews:(BOOL)fp8;
- (void)setAnchorPoint:(struct CGPoint)fp8 boundaryRect:(struct CGRect)fp16 animate:(BOOL)fp32;
- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)fadeOutWithDuration:(float)fp8;
- (void)_markDidMoveCalled;
- (void)completeBounceAnimation;
- (void)addTarget:(id)fp8 action:(SEL)fp12;
- (void)removeTarget:(id)fp8;
@property(retain) id delegate;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;

@end

