/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIView.h>
#import <UIKit2/CDStructures.h>

@class UIClippedImageView, UIImageView, UIKeyboardReturnKeyView, UIKeyboardSpaceKeyView;

@interface UIKeyboardSublayout : UIView
{
    UIImageView *m_imageView;
    UIClippedImageView *m_activeImageView;
    UIImageView *m_shiftImageView;
    UIClippedImageView *m_shiftActiveImageView;
    UIImageView *m_shiftButtonImageView;
    UIImageView *m_shiftButtonInactiveImageView;
    UIImageView *m_autoShiftButtonImageView;
    UIImageView *m_shiftLockedButtonImageView;
    NSMutableDictionary *m_compositeImages;
    NSMutableDictionary *m_activeKeyViews;
    UIImageView *m_intlMoreImageView;
    UIImageView *m_intlSwitchImageView;
    UIImageView *m_intlSwitchActiveImageView;
    UIImageView *m_nonIntlMoreImageView;
    UIImageView *m_deleteImageView;
    UIImageView *m_deleteActiveImageView;
    UIKeyboardSpaceKeyView *m_spaceKeyView;
    UIKeyboardReturnKeyView *m_returnKeyView;
    NSMutableArray *m_extraImageViews;
    struct UIKeyDefinition* m_keys;
    unsigned int m_keysCount;
    struct __CFDictionary *m_replacementKeys;
    NSMutableDictionary *m_replacementImageViews;
    BOOL m_usesAutoShift;
    BOOL m_isShiftKeyPlaneChooser;
    BOOL m_registersKeyCentroids;
    BOOL m_usesKeyCharges;
    BOOL m_internationalKeyIsActivated;
}

+ (id)sublayoutWithFrame:(struct CGRect)fp8 imagePaths:(id)fp24 keys:(const UIKeyDefinition*)fp28 keysCount:(unsigned int)fp32;

// This is just a convenient method for -initWithFrame:compositeImagePaths:keys:keyCount:
+ (UIKeyboardSublayout*)compositedSublayoutWithFrame:(struct CGRect)frame compositeImagePaths:(NSArray*)imagePaths keys:(const UIKeyDefinition[])keyDefs keysCount:(unsigned int)length;

- (id)initWithFrame:(struct CGRect)fp8 imagePaths:(id)fp24 keys:(const UIKeyDefinition*)fp28 keysCount:(unsigned int)fp32;

// Construct a sublayout with composite image.
//  - frame is (0, 0, width, height).
//  - imagePaths is an array of 2 elements containing the images before & after shift key is clicked.
//  - keys is an array of key definition.
- (UIKeyboardSublayout*)initWithFrame:(struct CGRect)frame compositeImagePaths:(NSArray*)imagePaths keys:(const UIKeyDefinition[])keyDefs keysCount:(unsigned int)length;

- (void)dealloc;
- (void)setUsesAutoShift:(BOOL)fp8;
- (BOOL)usesAutoShift;
- (void)setIsShiftKeyPlaneChooser:(BOOL)fp8;
- (BOOL)isShiftKeyPlaneChooser;
- (void)registerKeyAreaZephyr:(struct CGPoint)fp8 keyRect:(struct CGRect)fp16 keyCode:(int)fp32 keyString:(id)fp36 keyShiftString:(id)fp40;
- (void)registerKeyCentroids;
- (void)setRegistersKeyCentroids:(BOOL)doReg;
- (BOOL)usesKeyCharges;
- (void)setUsesKeyCharges:(BOOL)useKeyCharge;

- (void)setShiftButtonImage:(UIImage*)fp8 frame:(struct CGRect)fp12;
- (void)setShiftInactiveButtonImage:(UIImage*)fp8 frame:(struct CGRect)fp12;
- (void)setAutoShiftButtonImage:(UIImage*)fp8 frame:(struct CGRect)fp12;
- (void)setShiftLockedButtonImage:(UIImage*)fp8 frame:(struct CGRect)fp12;
- (void)setDeleteButtonImage:(UIImage*)fp8 frame:(struct CGRect)fp12;
- (void)setDeleteActiveButtonImage:(UIImage*)fp8 frame:(struct CGRect)fp12;
- (void)setCompositeImage:(UIImage*)fp8 forKey:(NSString*)fp12;

- (id)compositeImageForKey:(id)fp8;
- (void)addReplacementKeyboardKey:(UIKeyDefinition*)fp8 forKey:(id)fp12;
- (void)addReplacementImageView:(id)fp8 inputMode:(id)fp12 shift:(BOOL)fp16;
- (void)addExtraImageView:(id)fp8;
- (void)addPartialLayoutViewWithFrame:(struct CGRect)fp8 imageName:(id)fp24 visibleOrigin:(struct CGPoint)fp28;
- (void)addSpaceKeyViewIfNeeded;
- (void)addSpaceKeyViewIfNeeded:(id)fp8;
- (id)createSpaceKeyViewWithFrame:(struct CGRect)fp8 orientation:(int)fp24 style:(int)fp28;
- (void)setSpaceKeyView:(id)fp8;
- (void)addReturnKeyViewIfNeeded;
- (void)addReturnKeyViewIfNeeded:(id)fp8;
- (id)createReturnKeyViewWithFrame:(struct CGRect)fp8 orientation:(int)fp24 style:(int)fp28;
- (void)setReturnKeyView:(id)fp8;
- (id)internationalImageName:(int)fp8 forKeyboard:(id)fp12 orientation:(int)fp16;

- (void)addInternationalKeyIfNeeded:(NSString*)fp8;

- (BOOL)hitInternationalKey:(struct CGPoint)fp8;
- (void)activateInternationalKey;
- (BOOL)internationalKeyIsActivated;
- (void)deactivateInternationalKey;
- (void)bringKeySubviewsToFront;
- (id)scriptingInfoWithChildren;

@end

